version: "3"
services:
  opendj:
    image: osivia/opendj:cloud-ens
    ports:
      - 389:389
    volumes:
      - opendj-data:/opt/opendj/db
  portal:
    image: osivia/portal:5.0
    environment:
      - TZ=Europe/Paris
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    ports:
      - 8000:8000
      - 8080:8080
    entrypoint:
      - /usr/local/tomcat/bin/catalina.sh
      - jpda
      - run
  nuxeo:
    image: osivia/index-nuxeo:5.0
    environment:
      - LDAP_HOST=opendj
      - NUXEO_DB_HOST=postgres
      - NUXEO_ES_CLUSTER=cloud-ens-cluster
      - NUXEO_ES_NODES=es:9300
    ports:
      - 8081:8081
      - 8788:8000
    volumes:
      - nuxeo-data:/data
    depends_on:
      - postgres
      - es
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=osivia
      - POSTGRES_USER=nuxeo
      - POSTGRES_DB=nuxeodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  es:
    image: elasticsearch:1.7.6
    command: elasticsearch -Des.cluster.name=cloud-ens-cluster
    volumes:
      - es-data:/usr/share/elasticsearch/data      
volumes:
  nuxeo-data:
  opendj-data:
  postgres-data:
  es-data:
